### ISSUE TITLE
Event naming

### ISSUE THREAD

**Issue by ayamflow** [frolic/vue-viewport#1]
Cool plugin!

I just have one remark: why not using the node convention for the events names ?
Something like `viewport:enter` / `viewport:leave` which would reduce the risk of typo.
Also, more readable.

**Comment by frolic** [comment]
The event names were chosen to reflect the naming of browser events (`mouseenter`, `mouseleave`, etc.), since this is a browser-oriented plugin.

**Comment by ayamflow** [comment]
Ah! Didn't think of that :) Well done then
